version: '3.8'

services:

  auth-db:
    container_name: auth-db
    image: postgres
    restart: always
    networks:
      - vendas-network
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth

  produto-db:
    container_name: produto-db
    image: postgres
    restart: always
    networks:
      - vendas-network
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=produto

  vendas-db:
    container_name: vendas-db
    image: mongo:latest
    restart: always
    networks:
      - vendas-network
    ports:
      - 27017:27017
      - 28017:28017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  rabbitmq-vendas:
    container_name: rabbitmq
    image: rabbitmq:3.8-management
    networks:
      - vendas-network
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  
  auth-api:
    build: './auth-api'
    image: auth-api:1.0
    container_name: auth-api
    depends_on:
      - auth-db
    networks:
      - vendas-network
    ports:
      - 8080:8080
    environment:
      - PORT=8080
  
  vendas-api:
    build: './vendas-api'
    image: vendas-api:1.0
    container_name: vendas-api
    depends_on:
      - vendas-db
      - produto-api
      - rabbitmq-vendas
    networks:
      - vendas-network
    ports:
      - 8082:8082
    environment:
      - PORT=8082
    
  produto-api:
    build: './produto-api'
    image: produto-api:1.0
    container_name: produto-api
    depends_on:
      - produto-db
      - rabbitmq-vendas
    networks:
      - vendas-network
    ports:
      - 8081:8081
    environment:
      - PORT=8081


networks:
  vendas-network:
    driver: bridge

