server:
  port: ${PORT:8081}
spring:
  application:
    name: produto-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/produto
    username: postgres
    password: postgres
    initialization-mode: always
    initialize: true
    continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  mvn:
    log-resolved-exception: false

